# Generated by Django 4.2.4 on 2023-09-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veges", "0002_receipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="receipe_view_count",
            field=models.IntegerField(default=1),
        ),
    ]
