# Generated by Django 4.2.4 on 2023-08-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("age", models.IntegerField(default=20)),
                ("email", models.EmailField(max_length=254)),
                ("place", models.CharField(max_length=40)),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
