# Generated by Django 4.2.4 on 2023-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "p_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
            ],
        ),
    ]
